spring.application.name=taco-cloud
server.servlet.context-path=/taco_cloud_api

# Datasource (used by JPA/Hibernate)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.enabled=true

#JWT token
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}

# apis
stripe.apiKey=${STRIPE.API.KEY}

# Load .env file
spring.config.import=optional:file:.env[.properties]

